language: node_js
dist: precise
node_js:
- 7
branches:
    only:
    - source
before_script:
- npm install -g grunt
- npm install -g handlebars-helpers
script: grunt
after_success:
- bash ./deploy.sh
env:
    global:
    - ENCRYPTION_LABEL: "2ed699ca3770"
    - COMMIT_AUTHOR_EMAIL: "MCResourcePile@gmail.com"
