language: node_js
node_js:
- stable
branches:
    only:
    - source
before_script:
- npm install -g grunt
script: grunt
after_success:
- bash ./deploy.sh
env:
    global:
    - ENCRYPTION_LABEL: "2ed699ca3770"
    - COMMIT_AUTHOR_EMAIL: "MCResourcePile@gmail.com"
